In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

%matplotlib inline

In [ ]:
df = pd.read_csv('sample_data/column_2C_weka.csv')
df.head()

pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis     class
0         63.027818            22.552586  ...                 -0.254400  Abnormal
1         39.056951            10.060991  ...                  4.564259  Abnormal
2         68.832021            22.218482  ...                 -3.530317  Abnormal
3         69.297008            24.652878  ...                 11.211523  Abnormal
4         49.712859             9.652075  ...                  7.918501  Abnormal

[5 rows x 7 columns]

In [ ]:
df.columns

Index(['pelvic_incidence', 'pelvic_tilt numeric', 'lumbar_lordosis_angle',
       'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'class'],
      dtype='object')

In [ ]:
l1 = LabelEncoder()
label = l1.fit_transform(df["class"])
Data = df.drop("class", axis='columns')
Data["class"] = label

In [ ]:
Data.head()

pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis  class
0         63.027818            22.552586  ...                 -0.254400      0
1         39.056951            10.060991  ...                  4.564259      0
2         68.832021            22.218482  ...                 -3.530317      0
3         69.297008            24.652878  ...                 11.211523      0
4         49.712859             9.652075  ...                  7.918501      0

[5 rows x 7 columns]

### **Buat X_Train dan Y_Train**

In [ ]:
X_Data = Data[['pelvic_incidence', 'pelvic_tilt numeric', 'lumbar_lordosis_angle',
       'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis','class']]
Y_Data = Data["class"]

### **Normalisasi MinMax**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X_Data.tail(4)

pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis  class
306         53.936748            20.721496  ...                 -0.421010      1
307         61.446597            22.694968  ...                 -2.707880      1
308         45.252792             8.693157  ...                  0.214750      1
309         33.841641             5.073991  ...                 -0.199249      1

[4 rows x 7 columns]

In [ ]:
scalar = MinMaxScaler()
scalar.fit(X_Data)
New_Data = scalar.transform(X_Data)

In [ ]:
New_Data

array([[0.35568788, 0.51989984, 0.22917997, 0.2508573 , 0.30746116,
        0.02514839],
       [0.12450104, 0.2967831 , 0.09857833, 0.14462935, 0.47664891,
        0.03636497],
       [0.41166648, 0.51393229, 0.32299466, 0.30766054, 0.38609692,
        0.0175229 ],
       ...,
       [0.34043781, 0.52244298, 0.28789745, 0.23490726, 0.59779618,
        0.01943732],
       [0.18425678, 0.27235174, 0.24684569, 0.21462279, 0.52117504,
        0.02624045],
       [0.07420202, 0.20770855, 0.20261992, 0.14251659, 0.57924032,
        0.02527676]])

### **Normalisasi Z Score**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
Y_Data.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [ ]:
scalar = StandardScaler()
scalar.fit(X_Data)
New_Data = scalar.transform(X_Data)

In [ ]:
New_Data

array([[ 0.14708636,  0.50136873, -0.6651769 , ..., -1.4476468 ,
        -0.70805942, -0.69006556],
       [-1.24586434, -0.74876898, -1.45300075, ..., -0.26438488,
        -0.57955637, -0.69006556],
       [ 0.4843695 ,  0.46793218, -0.09926175, ..., -0.89768556,
        -0.79542095, -0.69006556],
       ...,
       [ 0.05520137,  0.51561812, -0.31097748, ...,  0.58289256,
        -0.77348834,  1.44913767],
       [-0.88582307, -0.88565951, -0.55861259, ...,  0.04702109,
        -0.69554822,  1.44913767],
       [-1.54892681, -1.24785954, -0.82539423, ...,  0.45311695,
        -0.70658867,  1.44913767]])

### DOwnload


In [ ]:
from numpy import asarray
from numpy import savetxt


data = New_Data
savetxt('sample_data/data.csv',data, delimiter=',',header='pelvic_incidence,pelvic_tilt numeric,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,class');

In [ ]:
df = pd.read_csv('sample_data/data.csv')
df.head()

# pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis     class
0            0.147086             0.501369  ...                 -0.708059 -0.690066
1           -1.245864            -0.748769  ...                 -0.579556 -0.690066
2            0.484370             0.467932  ...                 -0.795421 -0.690066
3            0.511390             0.711562  ...                 -0.402288 -0.690066
4           -0.626648            -0.789693  ...                 -0.490106 -0.690066

[5 rows x 7 columns]

### **KNN**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data=pd.read_csv('sample_data/train.csv')
df=pd.DataFrame(data,columns=['# pelvic_incidence', 'pelvic_tilt numeric', 'lumbar_lordosis_angle', 'sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'class'])
X=np.asarray(data)
x_train=df.iloc[:,:-1]
y_train=df.iloc[:,-1]

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
x_train.head()

# pelvic_incidence  ...  degree_spondylolisthesis
0            0.355688  ...                  0.025148
1            0.124501  ...                  0.036365
2            0.411666  ...                  0.017523
3            0.416151  ...                  0.051838
4            0.227272  ...                  0.044173

[5 rows x 6 columns]

In [ ]:
y_train.tail()

227    1.0
228    1.0
229    1.0
230    1.0
231    1.0
Name: class, dtype: float64

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5,
                         weights='uniform',
                         algorithm='auto',
                         metric='euclidean')

knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
datavalidasi=pd.read_csv('sample_data/test.csv')
df2=pd.DataFrame(datavalidasi,columns=['# pelvic_incidence', 'pelvic_tilt numeric', 'lumbar_lordosis_angle','sacral_slope', 'pelvic_radius', 'degree_spondylolisthesis', 'class'])
X2=np.asarray(datavalidasi)
x_val=df2.iloc[:,:-1]
y_val=df2.iloc[:,-1]

y_pred=knn.predict(x_val)


In [ ]:
x_val.tail()

# pelvic_incidence  ...  degree_spondylolisthesis
73            0.380609  ...                  0.016236
74            0.267761  ...                  0.037552
75            0.163667  ...                  0.028001
76            0.140186  ...                  0.019894
77            0.111722  ...                  0.057591

[5 rows x 6 columns]

In [ ]:
y_val.tail()

73    1.0
74    1.0
75    1.0
76    1.0
77    1.0
Name: class, dtype: float64

In [ ]:
# Evaluate the training and test score
print('Training accuracy score: %.2f' % knn.score(x_train, y_train))
print('Validation accuracy score: %.2f' % knn.score(x_val, y_val))

Training accuracy score: 0.84
Validation accuracy score: 0.81


In [ ]:
print(confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred))

[[50  3]
 [12 13]]
              precision    recall  f1-score   support

         0.0       0.81      0.94      0.87        53
         1.0       0.81      0.52      0.63        25

    accuracy                           0.81        78
   macro avg       0.81      0.73      0.75        78
weighted avg       0.81      0.81      0.79        78



### **UJI DATA BARU**

In [ ]:
uji=np.asarray([[0.6,1,1,1,0.70,0.05]])

In [ ]:
y_pred=knn.predict(uji)
print(y_pred)

[0.]
